"""
Django settings for prestamos_app project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import coin_app_backend.local_settings as local_settings

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = local_settings.BASE_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = local_settings.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = local_settings.DEBUG

ALLOWED_HOSTS = local_settings.ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = local_settings.INSTALLED_APPS

MIDDLEWARE = local_settings.MIDDLEWARE

ROOT_URLCONF = local_settings.ROOT_URLCONF

TEMPLATES = local_settings.TEMPLATES

WSGI_APPLICATION = local_settings.WSGI_APPLICATION


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = local_settings.DATABASES


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = local_settings.AUTH_PASSWORD_VALIDATORS

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = local_settings.LANGUAGE_CODE

TIME_ZONE = local_settings.TIME_ZONE

USE_I18N = local_settings.USE_I18N

USE_L10N = local_settings.USE_L10N

USE_TZ = local_settings.USE_TZ


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = local_settings.STATIC_URL

STATICFILES_DIRS = local_settings.STATICFILES_DIRS

# Session expire at browser close 

SESSION_EXPIRE_AT_BROWSER_CLOSE = local_settings.SESSION_EXPIRE_AT_BROWSER_CLOSE

# Login and Logout urls

LOGIN_URL = local_settings.LOGIN_URL
LOGIN_REDIRECT_URL = local_settings.LOGIN_REDIRECT_URL

LOGOUT_URL = local_settings.LOGOUT_URL
LOGOUT_REDIRECT_URL = local_settings.LOGOUT_REDIRECT_URL

# Auth user model

AUTH_USER_MODEL = local_settings.AUTH_USER_MODEL
